# Generated by Django 2.0.7 on 2018-08-06 12:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessagemodel',
            name='date_published',
        ),
        migrations.RemoveField(
            model_name='chatmessagemodel',
            name='message_html',
        ),
        migrations.RemoveField(
            model_name='chatroommodel',
            name='date_published',
        ),
        migrations.AddField(
            model_name='chatmessagemodel',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='chatroommodel',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
