# Generated by Django 2.0.7 on 2018-08-08 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0002_auto_20180806_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessagemodel',
            name='read',
            field=models.BooleanField(default=False, verbose_name='Прочитано'),
        ),
    ]
