# Generated by Django 2.0.7 on 2018-08-10 12:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0007_chatmessagemodel_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroommodel',
            name='last_updated_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
