# Generated by Django 2.0.7 on 2018-10-16 11:01

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='first_name',
            field=models.CharField(default='Аноним', max_length=30),
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='last_name',
            field=models.CharField(default='Аноним', max_length=150),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания профиля'),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='phone',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Некорректный номер телефона. Укажите номер без разделительных знаков, "+" и международного кода (пример: 9999999999)', regex='^[0-9]{9,16}$')], verbose_name='Номер телефона'),
        ),
    ]
