# Generated by Django 2.0.7 on 2018-10-17 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_app', '0002_auto_20181016_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='birthdate',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
    ]
